apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kubesimplify
  name: kubesimplify
spec:
  initContainers:
  - name: friday-init
    image: busybox
    command: ['sh', '-c', 'echo "Hello world!" | tee tmp/index.html']
    volumeMounts:
    - name:  demo
      mountPath: "/tmp/"
  containers:
  - image: nginx
    name: kubesimplify
    resources: {}
    volumeMounts:
    - name: demo
      mountPath: /usr/share/nginx/html
  volumes:
  - name: demo
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}