apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer
  name: multicontainer
spec:
  initContainers:
  - image: busybox
    name: busybox
    resources: {}
    restartPolicy: Always
    command: ["sleep", "100"]
  containers:
  - image: nginx
    name: nginx
    resources: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}