apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rockstar
  name: rockstar
spec:
  nodeName: node01
  containers:
  - image: nginx
    name: rockstar
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}