apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:

  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: nginx
              # - weight: 100
              # podAffinityTerm:
              #   labelSelector:
              #     matchExpressions:
              #     - key: app
              #       operator: In
              #       values:
              #       - nginx
                topologyKey: kubernetes.io/hostname
status: {}

